### ISSUE TITLE
Release it to Github Pages

### ISSUE THREAD

**Issue by lancedikson** [bowser-js/bowser-online#1]
We need to setup a proper releasing process to GH Pages

**Comment by ibc** [comment]
I've ~0 experience with GH Pages but should not be so hard. BTW not sure how to "automatize" it. I assume that, for every new bowser version, this project should be updated with the new bowser NPM version, is that right?

**Comment by lancedikson** [comment]
I guess we could use a CDN with the tag `latest` to load always fresh bowser version: https://cdn.jsdelivr.net/npm/bowser@latest/es5.js. It's simple and no need to redeploy it every time a new version comes out.

**Comment by ibc** [comment]
Wow, I didn't know about jsDelivr!

So, do you mean that I should remove `bowser` from package.json of `browser-online` project and instead add it via `<script>` tag pointing to that CDN?

**Comment by ibc** [comment]
Friendly ping. Is there any chance to have this published in `bowser` site?

**Comment by lancedikson** [comment]
Hi, @ibc. Sorry, I have been quite busy with work-related stuff. I'm afraid, I won't have enough time soon, so would you like to publish it on Github Pages by yourself? :) I maintainer's rights, so I guess, you should be able to do that.

**Comment by ibc** [comment]
Habemus site:

https://bowser-js.github.io/bowser-online/
